controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - L4_L3_joint
      - L5_L4_joint
      - L2_L3_joint
      - L1_L2_joint
    interface_name:
      - position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
